# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Sanitize the bot's token
        run: |
          stty -echo
          sed -i "s/BotConstant.BOT_TOKEN_STRING/\"${{ secrets.BOT_TOKEN }}\"/" src/com/deliburd/bot/burdbot/Main.java
          stty echo
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload jar to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_FTP_KEY }}
          passphrase: ${{ secrets.SSH_FTP_PASSPHRASE }}
          source: "build/libs/*-all.jar"
          target: "burdbot"
      - name: Restart BurdBot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_COMMAND_KEY }}
          passphrase: ${{ secrets.SSH_COMMAND_PASSPHRASE }}
          script: |
            stty -echo
            pkill burdbot.sh
            stty echo
